version: '3.8'

services:
  # Redis 服務
  redis:
    image: redis:7-alpine
    container_name: eisenhower-redis-dev
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data_dev:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # 後端 API 服務
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eisenhower-backend-dev
    ports:
      - "${BACKEND_PORT:-5001}:5001"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - PORT=5001
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules

  # 前端服務 (開發模式)
  frontend:
    build:
      context: ./frontend-2
      dockerfile: Dockerfile.dev
    container_name: eisenhower-frontend-dev
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - VITE_API_URL=http://localhost:5001
      - VITE_ENV=development
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  redis_data_dev: 